import express from "express";
import { getAllCategories } from "../controllers/categories/getAllCategories.js";
import asyncWrapper from "../middlewares/asyncWrapper.js";
import { addCategory } from "../controllers/categories/add.js";
import { protect } from "../middlewares/auth.js";
import { getAllProductsByCategory } from "../controllers/categories/getCategoryProducts.js";
import { getAllCategoriesWithItsProducts } from "../controllers/categories/getAllCategoriesWithProducts.js";
import { removeCategory } from "../controllers/categories/remove.js";
import { authorizeRoles } from "../middlewares/authRole.js";
import upload from "../config/multer.js";
const Router = express.Router();
Router.post("/", protect,authorizeRoles("admin"),upload.single("image"), asyncWrapper(addCategory));
Router.get("/", protect,asyncWrapper(getAllCategories));
Router.get("/products", protect, asyncWrapper(getAllCategoriesWithItsProducts));
Router.get("/:categoryId",protect, asyncWrapper(getAllProductsByCategory));
Router.delete("/:categoryId", protect,authorizeRoles("admin"), asyncWrapper(removeCategory));
export default Router;
